Implementfilesend
boilerplate-builder-capstone/bouiler-plate-builder pull request #31
Opened 2021-06-11 02:02 UTC by kfless12

Implemented EJS and sequlize together with the server.
Made several adjustments to the sequelize file snippets and naming structures of some of the snippets "filename" (for working purposes)
connected the download button to send over the boiler plate file as a download

2021-06-11 21:39 UTC, king-ellie requested changes
Awesome work, thank you so much! Mostly the zipHelper and createFile calls just need to be updated to async/have "await" in front of them. Seriously amazing how you walked through the logic to build these zip files

2021-06-11 21:39 UTC, king-ellie commented on server/api/zippedBoilerPlate.js
>  function zipHelper(fileString, arrObject){
zipHelper should be async, and all zipHelper calls should have await in front of them

2021-06-11 21:39 UTC, king-ellie commented on server/api/zippedBoilerPlate.js
> +    let appjs = createFile('R2', boiler)
I believe appjs should only be created if boiler.react is truthy. In other words, if a user says react: false, all they should receive for the front end is a client folder with index.html in it

2021-06-11 21:39 UTC, king-ellie commented on server/api/zippedBoilerPlate.js
> +async function createFile(key, variable){
All calls of createFile need to have "await" in front of them

2021-06-12 14:13 UTC, king-ellie approved these changes

2021-06-12 14:23 UTC, mpiech1813 approved these changes

2021-06-12 14:25 UTC, merged